// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0EtmkSkpKoYTEQ-68H7mcDO76Lu1gLFE',
    appId: '1:11586362177:web:83d8c2d7d4222a65c0dfc0',
    messagingSenderId: '11586362177',
    projectId: 'auth-project-10cb1',
    authDomain: 'auth-project-10cb1.firebaseapp.com',
    storageBucket: 'auth-project-10cb1.firebasestorage.app',
    measurementId: 'G-91L26NGNCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuwCqhqAZdMZEKl6PDZyxSIHoPj2vl0rM',
    appId: '1:11586362177:android:658c9cbe1e8e0e25c0dfc0',
    messagingSenderId: '11586362177',
    projectId: 'auth-project-10cb1',
    storageBucket: 'auth-project-10cb1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0EtmkSkpKoYTEQ-68H7mcDO76Lu1gLFE',
    appId: '1:11586362177:web:87b7d830241d5bf7c0dfc0',
    messagingSenderId: '11586362177',
    projectId: 'auth-project-10cb1',
    authDomain: 'auth-project-10cb1.firebaseapp.com',
    storageBucket: 'auth-project-10cb1.firebasestorage.app',
    measurementId: 'G-H15XFDXWYH',
  );
}
