// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEBvH-_wPwMtH4R9xPI9925asg4g4RdX8',
    appId: '1:642610301097:web:758f4f7a160eebe99b81b8',
    messagingSenderId: '642610301097',
    projectId: 'notesdatabase-d6f45',
    authDomain: 'notesdatabase-d6f45.firebaseapp.com',
    storageBucket: 'notesdatabase-d6f45.firebasestorage.app',
    measurementId: 'G-PK1PHJT3EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwDZF0fJ-A4lnQanUJyVoE6gAxQbvA4a0',
    appId: '1:642610301097:android:43f5c908882480539b81b8',
    messagingSenderId: '642610301097',
    projectId: 'notesdatabase-d6f45',
    storageBucket: 'notesdatabase-d6f45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRy34P9gT9itbyjdbDR1zjBfdFkJIsPns',
    appId: '1:642610301097:ios:ba595b462ac824329b81b8',
    messagingSenderId: '642610301097',
    projectId: 'notesdatabase-d6f45',
    storageBucket: 'notesdatabase-d6f45.firebasestorage.app',
    iosBundleId: 'com.example.apkNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRy34P9gT9itbyjdbDR1zjBfdFkJIsPns',
    appId: '1:642610301097:ios:ba595b462ac824329b81b8',
    messagingSenderId: '642610301097',
    projectId: 'notesdatabase-d6f45',
    storageBucket: 'notesdatabase-d6f45.firebasestorage.app',
    iosBundleId: 'com.example.apkNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEBvH-_wPwMtH4R9xPI9925asg4g4RdX8',
    appId: '1:642610301097:web:e80311317713469c9b81b8',
    messagingSenderId: '642610301097',
    projectId: 'notesdatabase-d6f45',
    authDomain: 'notesdatabase-d6f45.firebaseapp.com',
    storageBucket: 'notesdatabase-d6f45.firebasestorage.app',
    measurementId: 'G-YZXQW69RC6',
  );
}
